name: build and test with maven
run-name: mvn:build:test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-mvn-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: execute mvn build
        run: mvn package -DskipTests

      - name: execute mvn tests
        run: mvn test